name: conselheiro
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  cloud_firestore: ^4.5.0
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # to generate, just run: flutter pub run build_runner build
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  test: ^1.22.0

flutter:
  uses-material-design: true
